name: dartotsu_extension_bridge
description: "A new Flutter plugin project."
version: 0.0.4
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  http: ^1.4.0
  d4rt: ^0.1.4
  get: ^4.7.2
  path_provider: ^2.1.5
  path: ^1.9.1
  http_interceptor: ^2.0.0
  html: ^0.15.6
  intl: ^0.20.2
  flutter_inappwebview: ^6.2.0-beta.2
  pseudom: ^1.0.1
  js_packer: ^0.0.6
  flutter_qjs:
    git:
      url: https://github.com/kodjodevf/flutter_qjs.git
      ref: main
  epubx:
    git:
      url: https://github.com/kodjodevf/epubx.dart.git
      ref: dev
  install_plugin: ^2.1.0
  xml: ^6.6.1
  dart_style: ^3.1.2
  crypto: ^3.0.3
  blockchain_utils: ^5.2.0
  xpath_selector: ^3.0.2
  xpath_selector_html_parser: ^3.0.1
  xpath_selector_xml_parser: ^3.0.1
  installed_apps: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build: ^3.0.2

dependency_overrides:
  js: ^0.7.2
  petitparser: ^7.0.1
  build: ^3.0.2
  analyzer: ^8.0.0
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0
  test_api: ^0.7.7
  source_gen: ^3.1.0
  objectbox: 
    git:
      url: https://github.com/objectbox/objectbox-dart.git
      path: objectbox
  objectbox_flutter_libs:
    git:
      url: https://github.com/objectbox/objectbox-dart.git
      path: flutter_libs
  objectbox_generator:
    git:
      url: https://github.com/objectbox/objectbox-dart.git
      path: generator
  watcher: ^1.1.3

flutter:
  plugin:
    platforms:
      android:
        package: com.aayush262.dartotsu_extension_bridge
        pluginClass: DartotsuExtensionBridgePlugin
      ios:
        pluginClass: DartotsuExtensionBridgePlugin
      linux:
        pluginClass: DartotsuExtensionBridgePlugin
      macos:
        pluginClass: DartotsuExtensionBridgePlugin
      windows:
        pluginClass: DartotsuExtensionBridgePluginCApi
