name: dartotsu_extension_bridge
description: "A new Flutter plugin project."
version: 0.0.4
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  # Core & Utilities
  get: ^4.7.2
  path: ^1.9.1
  path_provider: ^2.1.5
  intl: ^0.20.2
  dio: ^5.0.0
  http_interceptor: ^2.0.0
  dart_style: ^3.1.1
  crypto: ^3.0.3
  blockchain_utils: ^5.2.0
  pseudom: ^1.0.1
  d4rt: ^0.1.4

  # HTML / XML Parsing
  html: ^0.15.6
  xml: ^6.6.1

  # WebView / JS
  flutter_inappwebview: ^6.2.0-beta.2
  flutter_qjs:
    git:
      url: https://github.com/kodjodevf/flutter_qjs.git
      ref: main

  # EPUB
  epubx:
    git:
      url: https://github.com/kodjodevf/epubx.dart.git
      ref: dev

  # Plugins
  plugin_platform_interface: ^2.1.0
  install_plugin: ^2.1.0
  appcheck: ^1.1.0
  package_info_plus: ^8.0.0
  
  # ObjectBox
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  # ObjectBox
  objectbox_generator: ^4.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.aayush262.dartotsu_extension_bridge
        pluginClass: DartotsuExtensionBridgePlugin
      ios:
        pluginClass: DartotsuExtensionBridgePlugin
      linux:
        pluginClass: DartotsuExtensionBridgePlugin
      macos:
        pluginClass: DartotsuExtensionBridgePlugin
      windows:
        pluginClass: DartotsuExtensionBridgePluginCApi
