name: dartotsu_extension_bridge
description: "A new Flutter plugin project."
version: 0.0.4
# homepage:
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  http: ^1.4.0
  d4rt: ^0.1.3
  get: ^4.7.2
  path_provider: ^2.1.5
  path: ^1.9.1
  http_interceptor: ^2.0.0
  html: ^0.15.6
  intl: ^0.20.2
  flutter_inappwebview: ^6.2.0-beta.2
  pseudom: ^1.0.1
  xpath_selector_html_parser: ^3.0.1
  js_packer: ^0.0.6
  crypto: ^3.0.6
  flutter_qjs:
    git:
      url: https://github.com/kodjodevf/flutter_qjs.git
      ref: main
  epubx:
    git:
      url: https://github.com/kodjodevf/epubx.dart.git
      ref: dev
  install_plugin: ^2.1.0
  device_apps: ^2.2.0
  dart_style: ^3.1.1
  build: ^2.4.1
  objectbox: ^4.3.0
  objectbox_flutter_libs: ^4.3.0
  cryptography: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.6
  objectbox_generator: ^4.3.0

flutter:
  plugin:
    platforms:
      android:
        package: com.aayush262.dartotsu_extension_bridge
        pluginClass: DartotsuExtensionBridgePlugin
      ios:
        pluginClass: DartotsuExtensionBridgePlugin
      linux:
        pluginClass: DartotsuExtensionBridgePlugin
      macos:
        pluginClass: DartotsuExtensionBridgePlugin
      windows:
        pluginClass: DartotsuExtensionBridgePluginCApi
